server:
  port: 8888

spring:
  profiles:
    active: native  # используем native-профиль, чтобы читать конфиги с файловой системы (или из classpath)
  cloud:
    config:
      server:
        native:
          # Перечисляем все варианты поиска конфигов
          # Можно использовать список директорий
          searchLocations:
            - classpath:config/telemetry/${app.aggregator}
            - classpath:config/telemetry/${app.analyzer}
            - classpath:config/telemetry/${app.collector}

# Определим переменные с именами проектов в этом же файле
app:
  aggregator: aggregator
  analyzer: analyzer
  collector: collector