server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:warehouse}
  cloud:
    config:
      discovery:
        enabled: ${CONFIG_DISCOVERY_ENABLED:true}
        service-id: ${CONFIG_SERVER_ID:config-server}
      fail-fast: ${CONFIG_FAIL_FAST:true}
      retry:
        max-attempts: ${CONFIG_RETRY_ATTEMPTS:5}
        initial-interval: ${CONFIG_RETRY_INITIAL:2000}
        max-interval: ${CONFIG_RETRY_MAX:10000}

  datasource:
    url: jdbc:postgresql://${WAREHOUSE_DB_HOST:localhost}:${WAREHOUSE_DB_PORT:5432}/${WAREHOUSE_DB_NAME:warehouse}
    username: ${WAREHOUSE_DB_USER:warehouse_user}
    password: ${WAREHOUSE_DB_PASSWORD:warehouse_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
