spring:
  application:
    name: collector  # Имя сервиса для Config Server.
      # По умолчанию Config Server вернёт collector.yml для профиля default.
    # При запросе http://localhost:8888/collector/default отдаст collector.yml.
    # Если обратиться к http://localhost:8888/collector/test,
    # попытается вернуть collector-test.yml + подмешать collector.yml.

  config:
    # Подключение к Config Server через псевдосхему "configserver:".
    # Если CONFIG_SERVER_URL не задана, используется http://localhost:8888.
    # Пример:
    #  - default профиль: http://localhost:8888/collector/default
    #  - test профиль:    http://localhost:8888/collector/test
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    config:
      # Если конфиг не загружен, приложение сразу падает (fail-fast).
      fail-fast: true

      # Настройка повторных попыток запроса к Config Server:
      retry:
        max-attempts: 5       # Кол-во попыток подключения
        initial-interval: 2000 # Пауза (мс) перед первой повторной попыткой
        max-interval: 10000    # Максимальный интервал пауз при экспоненциальном росте

