server:
  port: 8184

spring:
  application:
    name: order

  jackson:
    mapper:
      accept-case-insensitive-enums: true
      default-view-inclusion: true
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
      accept-empty-string-as-null-object: true
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      write-null-map-values: false
    default-property-inclusion: non_null

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
        max-interval: 10000
    circuitbreaker:
      resilience4j:
        instances:
          warehouse:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 10s
            permittedNumberOfCallsInHalfOpenState: 5
            registerHealthIndicator: true

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: order_user
    password: order_pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      payment-client:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

api:
  version: /api/v1
  order-path: /order
  return-path: /return
  payment-path: /payment
  payment-failed-path: /payment/failed
  delivery-path: /delivery
  delivery-failed-path: /delivery/failed
  completed-path: /completed
  calculate-total-cost-path: /calculate/total
  calculate-delivery-cost-path: /calculate/delivery
  assembly-path: /assembly
  assembly-failed-path: /assembly/failed
