spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.aggregator.deserializer.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
    topics:
      telemetry:
        sensors: telemetry.sensors.v1
        snapshots: telemetry.snapshots.v1

  application:
    name: aggregator
logging:
  level:
    root: INFO
