server:
  # 0 означает случайный свободный порт. Можно переопределять SERVER_PORT.
  port: ${SERVER_PORT:0}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:shopping-store}

  cloud:
    config:
      discovery:
        enabled: ${CONFIG_DISCOVERY_ENABLED:true}
        service-id: ${CONFIG_SERVER_ID:config-server}
      fail-fast: ${CONFIG_FAIL_FAST:true}
      retry:
        max-attempts: ${CONFIG_RETRY_ATTEMPTS:5}
        initial-interval: ${CONFIG_RETRY_INITIAL:2000}
        max-interval: ${CONFIG_RETRY_MAX:10000}
    circuitbreaker:
      resilience4j:
        instances:
          warehouse:
            slidingWindowSize: ${CIRCUIT_BREAKER_WINDOW_SIZE:10}
            failureRateThreshold: ${CIRCUIT_BREAKER_FAILURE_RATE:50}
            waitDurationInOpenState: ${CIRCUIT_BREAKER_WAIT_DURATION:10s}
            permittedNumberOfCallsInHalfOpenState: ${CIRCUIT_BREAKER_PERMITTED_CALLS:5}
            registerHealthIndicator: true

  datasource:
    # Настройки подключения к PostgreSQL
    url: jdbc:postgresql://${SHOPPING_STORE_DB_HOST:localhost}:${SHOPPING_STORE_DB_PORT:5432}/${SHOPPING_STORE_DB_NAME:shopping_store}
    username: ${SHOPPING_STORE_DB_USER:store_user}
    password: ${SHOPPING_STORE_DB_PASSWORD:store_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: ${SHOW_SQL:false}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP:true}
    lease-renewal-interval-in-seconds: ${EUREKA_LEASE_RENEW:10}
    lease-expiration-duration-in-seconds: ${EUREKA_LEASE_EXPIRE:30}

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      warehouse-client:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:basic}

logging:
  level:
    # Общий уровень логирования
    root: ${LOG_LEVEL:INFO}
    # Дополнительная детализация в нужных пакетах
    ru.yandex.practicum: ${APP_LOG_LEVEL:DEBUG}
    ru.yandex.practicum.warehouse.client.ApiApi: ${FEIGN_LOG_LEVEL:DEBUG}
